version: '3'

networks: 
  mynetworkTP6-part2: 
    driver: bridge

services :
  mongodb:
    image: mongo
    networks: 
      - mynetworkTP6-part2
    ports: 
      - 27017:27017
    container_name: mongodb-containerTP6-part2
    volumes:
      - mongodb-volume:/data/db

  flaskapp: 
    build: .
    ports:
      - 5000:5000 
    networks:
      - mynetworkTP6-part2
    depends_on:
      - mongodb
    container_name: flaskappTP6
    volumes:
      - ./filedisplayed.txt:/app/filedisplayed.txt
  


