version: '3'

networks: 
  mynetworkTP6-part2: 
    driver: bridge

services :
  mongodb:
    image: mongo
    networks: 
      - mynetworkTP6-part2
    volumes:
      - type: bind
        source: ./mongodb-data
        target: /data/db
    ports: 
      - 27017:27017
    container_name: mongodb-container6


  flaskapp: 
    build: .
    ports:
      - 5000:5000 
    networks:
      - mynetworkTP6-part2
    container_name: flaskappTP6-part2
    depends_on:
      - mongodb
    volumes:
      - type: bind
        source: ./filedisplayed.txt
        target: /app/filedisplayed.txt

